### ISSUE TITLE
not an issue but only way to communicate

### ISSUE THREAD

**Issue by QuickWick123** [secure-77/G19AppletLuncher#2]
Is it possible to make this exact app but with 12 hour time format?

https://drive.google.com/file/d/1mo2qXwvzgsYdw15A0TqF7hONSBU2GhCC/view?usp=share_link

G19 Retro Clock. It's beautiful.

**Comment by secure-77** [comment]
Hi, this clock APP in your link is not from me, so maybe you should try to contact the creator of this app
